<x-app-layout>
    <div class="py-12">
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
       <p>Hola esto es el dashboard</p>
    </div>
</x-app-layout>
