services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - /var/www/node_modules
      - /var/www/vendor
    networks:
      - laravel_network
    ports:
      - "8000:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: bash -c "php artisan optimize:clear && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: CyberStock_WMS
      MYSQL_ROOT_PASSWORD: 1234abcd.
      MYSQL_USER: rolu47
      MYSQL_PASSWORD: 1234abcd.
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  mysql_data:
